---
cache_dir: ~/Library/Caches/battleschool

sources:
#  local:
#    - playbook.yml

  url:
#    - name: playbook.yml
#      url: https://www.dropbox.com/s/9lza9ovgrv8m3jy/playbook.yml?dl=0

  git:
    - name: 'osx'
      repo: 'https://github.com/raskawa/ansible-osx'
      playbooks:
         - homebrew.yml                 #must come before any use of homebrew module
         - macports.yml                #must come before any use of macports module
         - oh-my-zsh.yml
         - homebrew.yml
         - cask.yml
         - atom.yml
         - chrome-stable.yml
         - dropbox.yml
         - evernote.yml
         - kaleidoscope.yml
         - skype.yml
         - webstorm.yml
#         - sshfs.yml
#         - flux.yml
         - github.yml
         - gitx.yml
         - iterm2.yml
         - sublime3.yml
         - vagrant.yml
         - virtualbox.yml
         - alfred.yml
#         - chrome-beta.yml
#         - chrome-canary.yml
         - karabiner.yml
#         - intellij-idea-ultimate15.yml
#         - java7.yml
#         - java6.yml
         - better-touch-tool.yml
#         - adium.yml
#         - libreoffice.yml
#         - seil.yml
#         - spectacle.yml
#         - sequel-pro.yml
         - skype.yml
#         - truecrypt.yml
#         - usb-overdrive.yml
         - xtra-finder.yml

    - name: 'myplaybooks'
      repo: 'https://github.com/raskawa/my-battleschool'
      playbooks:
        - docker.yml
        - myplaybook.yml